#!/bin/bash
if [ ! -f sftp-config.json ]; then
    printf "\n# Fatal Error \n - sftp-config.json not found!\n\n"
    exit 0
fi
echo "+ Project Files being synced local -> RDS"
bash syncAll 2> /dev/null > /dev/null 
USERNAME=`grep "user" sftp-config.json | awk {'print $2'} | sed 's/"//g' | sed 's/,//g'`
REMOTE_PATH=`grep "remote_path" sftp-config.json | awk {'print $2'} | sed 's/"//g' | sed 's/,//g'`
REMOTE_HOST=`grep "host" sftp-config.json | awk {'print $2'} | sed 's/"//g' | sed 's/,//g'`
echo "+ Killing old node instances"
ssh $USERNAME@$REMOTE_HOST "ps -u $USERNAME | grep node | awk '{print \$1}' | xargs kill 2> /dev/null "
echo "+ NodeJS started"
ssh $USERNAME@$REMOTE_HOST "cd $REMOTE_PATH/; forever -w server.js $USERNAME"
